image: elixir:1.7.4 #update this when we switch Elixir version

stages:
  - deploy

before_script:
  - apt-get update -qq && apt-get install -y -qq python3-pip && pip install awscli # Install the AWS SDK for pushing the docs
  - mix local.hex --force
  - mix local.rebar --force
  - 'MIX_ENV=dev mix deps.get'

pages:
  stage: deploy
  script:
  - MIX_ENV=dev mix docs
  - mv doc public # serve as GitLab Pages artifact
  - aws s3 sync public/ s3://${DOCS_STAGING_BUCKET}/docs/server/ --delete --exclude .git --exclude README.md --acl public-read # also copy docs to S3-served website
  - aws cloudfront create-invalidation --distribution-id ${DOCS_STAGING_DISTRIBUTION_ID} --paths '/docs/server/*' # invalidate CloudFront's cache to serve the new version
  artifacts:
    paths:
    - public
  only:
  - develop
