image: elixir:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
  - 'cd $CI_PROJECT_DIR'
  - mkdir public
  - MIX_ENV=dev mix deps.get
  - MIX_ENV=dev mix docs
  - mv doc public
  artifacts:
    paths:
    - public
  only:
  - develop
