image: elixir:latest

stages:
  - deploy

before_script:
  - mix local.hex --force
  - 'MIX_ENV=dev mix deps.get'

pages:
  stage: deploy
  script:
  - MIX_ENV=dev mix docs
  - mv doc public
  artifacts:
    paths:
    - public
  only:
  - develop
