image: elixir:1.7.4 #update this when we switch Elixir version

stages:
  - deploy

before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - 'MIX_ENV=dev mix deps.get'

pages:
  stage: deploy
  script:
  - MIX_ENV=dev mix docs
  - mv doc public
  artifacts:
    paths:
    - public
  only:
  - develop
