version: '3.5'

services:
  web:
    # Pull the image from dockerhub
    image: "moodlenet/moodlenet:latest"

    # Build the image first with: make build
    #image: "moodlenet:latest"
    ports:
      - "4000:4000"
    env_file:
      - config/docker.env
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    # volumes:
    #   - "./volumes/postgres:/var/lib/postgresql/data"
    # ports:
    #   - "5432:5432"
    env_file:
      - config/docker.env
