version: "3.5"

services:
  backend:
    # You can build your own image from the source running:
    # $ make build
    # $ make tag_latest
    image: "commonspub/commonspub:latest"
    restart: always
    ports:
      - "4088:4000" # you may want to comment this in production
      # - "80:80"
      # - "443:443"
    env_file:
      - config/prod/public.env
      - config/prod/secrets.env
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./uploads
        target: /var/www/uploads
  frontend:
    image: "caddy:alpine"
    restart: always
    ports:
      - "88:80"
      - "4438:443"
    env_file:
      - config/prod/public.env
    volumes:
      - type: bind
        source: ./config/deployment/caddy/Caddyfile2
        target: /etc/caddy/Caddyfile
        read_only: true
      - type: bind
        source: ./uploads
        target: /frontend/uploads
  db:
    image: postgis/postgis:12-3.0-alpine
    restart: always
    volumes:
      - "./data/postgres/prod:/var/lib/postgresql/data"
    # ports:
    #   - "5432:5432"
    env_file:
      - config/prod/public.env
      - config/prod/secrets.env
  search:
    image: getmeili/meilisearch:latest
    ports:
      - "7788:7700"
    volumes:
      - "./data/search/prod:/data.ms"
    env_file:
      - config/prod/public.env
      - config/prod/secrets.env
