version: "3.5"

services:
  backend:
    # You can build your own image from the source running:
    # $ make prod-build
    image: "commonspub/commonspub:prod-latest"
    restart: always
    ports:
      - "4010:4000" # you may want to comment this in production
      # - "80:80"
      # - "443:443"
    env_file:
      - config/prod/public.env
      - config/prod/secrets.env
    depends_on:
      - db
    volumes:
      - .:/opt/app
      - type: bind
        source: ./uploads
        target: /var/www/uploads
    # exclude the following dirs from being mounted:
      # - /opt/app/_build
  frontend:
    image: "caddy:alpine"
    restart: always
    ports:
      - "4009:80"
      # - "4443:4443"
    env_file:
      - config/prod/public.env
    volumes:
      - type: bind
        source: ./config/deployment/caddy/Caddyfile2
        target: /etc/caddy/Caddyfile
        read_only: true
      - type: bind
        source: ./uploads
        target: /frontend/uploads
        read_only: true
  db:
    image: postgis/postgis:12-3.0-alpine
    restart: always
    volumes:
      - "./data/postgres/prod:/var/lib/postgresql/data"
    # ports:
    #   - "5432:5432"
    env_file:
      - config/prod/public.env
      - config/prod/secrets.env
  search:
    image: getmeili/meilisearch:latest
    # ports:
    #   - "7700:7700"
    volumes:
      - "./data/search/prod:/data.ms"
    env_file:
      - config/prod/public.env
      - config/prod/secrets.env
